from importlib.metadata import PackageNotFoundError, version

from .parser import LiteParse, search_items
from .types import (
    AnnotationRect,
    DocumentAnnotation,
    LayoutBlock,
    LayoutCell,
    FormField,
    StructureTree,
    StructureTreeElement,
    ExtractedImage,
    ImageRect,
    LayoutComplexityStats,
    LiteParseConfig,
    PageComplexityStats,
    PageError,
    ParseResult,
    ParseBatch,
    DocumentMetadata,
    XfaPacket,
    ParsedPage,
    TextItem,
    WordBox,
    ScreenshotRect,
    ScreenshotResult,
    ScreenshotFormat,
    ScreenshotOptions,
    PngScreenshotOptions,
    PngCompression,
    ParseError,
    VectorGraphics,
    VectorLine,
    VectorShape,
)

try:
    __version__ = version("liteparse")
except PackageNotFoundError:  # source tree without installed dist metadata
    __version__ = "0.0.0+unknown"
__all__ = [
    "LiteParse",
    "AnnotationRect",
    "DocumentAnnotation",
    "LayoutBlock",
    "LayoutCell",
    "FormField",
    "StructureTree",
    "StructureTreeElement",
    "LiteParseConfig",
    "ParseResult",
    "PageError",
    "ParseBatch",
    "DocumentMetadata",
    "XfaPacket",
    "ParsedPage",
    "TextItem",
    "WordBox",
    "ScreenshotRect",
    "ScreenshotResult",
    "ScreenshotFormat",
    "ScreenshotOptions",
    "PngScreenshotOptions",
    "PngCompression",
    "PageComplexityStats",
    "LayoutComplexityStats",
    "ExtractedImage",
    "ImageRect",
    "ParseError",
    "search_items",
    "VectorGraphics",
    "VectorLine",
    "VectorShape",
]
